import * as TYPES from 'types/type';

export const productBank: TYPES.ProductType<number>[] = [
  {
    productName: 'Tshirt',
    productBrand: 'Nike',
    productDescription: 'Branded',
    productImage: {},
    productPrice: 5000,
    discount: 20,
    inStock: 25,
    onSale: 0,
  },
  {
    productName: 'Shoes',
    productBrand: 'Nike',
    productDescription: 'Branded',
    productImage: {},
    productPrice: 18000,
    discount: 20,
    inStock: 25,
    onSale: 1,
  },
  {
    productName: 'Trousers',
    productBrand: 'Nike',
    productDescription: 'Branded',
    productImage: {},
    productPrice: 2000,
    discount: 20,
    inStock: 25,
    onSale: 0,
  },
  {
    productName: 'Hoodie',
    productBrand: 'Nike',
    productDescription: 'Branded',
    productImage: {},
    productPrice: 8000,
    discount: 20,
    inStock: 25,
    onSale: 1,
  },
  {
    productName: 'Pant',
    productBrand: 'Nike',
    productDescription: 'Branded',
    productImage: {},
    productPrice: 4000,
    discount: 20,
    inStock: 25,
    onSale: 0,
  },
  {
    productName: 'Jacket',
    productBrand: 'Nike',
    productDescription: 'Branded',
    productImage: {},
    productPrice: 12000,
    discount: 20,
    inStock: 25,
    onSale: 1,
  },
];
